# Generated by Django 4.0.4 on 2022-06-16 16:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('coord', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_events', to='planning.planning')),
            ],
        ),
    ]
