# Generated by Django 4.0.5 on 2022-06-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='create',
            new_name='created',
        ),
    ]
