# Generated by Django 4.0.5 on 2022-06-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_create_event_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created']},
        ),
    ]
